### ISSUE TITLE
Istio stable-mesh test is broken

### ISSUE THREAD

**Issue by nak3** [knative-sandbox/net-istio#249]
Please refer to https://testgrid.knative.dev/serving#istio-stable-mesh.

Almost all tests became Red :skull: after https://github.com/knative/serving/commit/09986741f0bc6e369ed99370728ad715054656d5.

**Comment by tcnghia** [comment]
cc @mattmoor

**Comment by nak3** [comment]
I am suspecting this Istio's issue https://github.com/istio/istio/issues/23463. The DestinationRule and some behavior were different whether we have the port or not.

**Comment by tcnghia** [comment]
@nak3 I think this is fixed in 1.6?

**Comment by tcnghia** [comment]
cc @ZhiminXiang @JRBANCEL @Cynocracy

**Comment by JRBANCEL** [comment]
It is still broken.
The `webhook` Container of `webhook` Pod never gets ready ([example](https://storage.googleapis.com/knative-prow/logs/ci-knative-serving-istio-stable-mesh/1311832861287911424/build-log.txt)), because the probes defined [here](https://github.com/knative/serving/blob/master/config/core/deployments/webhook.yaml#L93):
```
2020-10-02T01:16:54.849646Z	error	Request to probe app failed: Get "https://localhost:8443/": remote error: tls: internal error, original URL path = /app-health/webhook/readyz app URL path = /
2020-10-02T01:16:55.347043Z	error	Request to probe app failed: Get "https://localhost:8443/": remote error: tls: internal error, original URL path = /app-health/webhook/livez app URL path = /
```

It might be an Istio issue, see this [similar issue](https://github.com/istio/istio/issues/18242).

**Comment by JRBANCEL** [comment]
What seems to be happening is that Kubelet does indeed call the modified probes (on Istio Proxy) and then the proxy calls the Webhook probes, but this fails with the not useful `remote error: tls: internal error`.
I suspect that it fails because this is endpoint uses a self-signed certificate.

**Comment by JRBANCEL** [comment]
Istio skips TLS validation: https://github.com/istio/istio/blob/master/pilot/cmd/pilot-agent/status/server.go#L421
So it is failing for another reason. In the `webhook` logs I see `2020/10/02 01:20:23 http: TLS handshake error from 127.0.0.1:55830: server key missing`.
Someone complained about this recently: https://github.com/knative/eventing/issues/4165

**Comment by nak3** [comment]
Closing. There are still some failures but they are tracked by https://github.com/knative-sandbox/net-istio/issues/340.
